import { useEffect, useState, type DragEvent, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { ArrowLeft, Check, GripVertical, Loader2, Pencil, Plus, RefreshCw, Trash2, X } from 'lucide-react';
import { hiringRoundService } from '@/services/hiring-round.service';
import { emailTemplateService } from '@/services/email-template.service';
import { jobService } from '@/services/job.service';
import type { HiringRound, HiringRoundRequest } from '@/types/hiring-round.types';

type EmailTemplateOption = { id: number; name: string };
const blankRound = (): HiringRoundRequest => ({ name: '', description: '', testLink: '', isFinalRound: false, passEmailTemplateId: null, failEmailTemplateId: null });
const optionalId = (value: string) => value === '' ? null : Number(value);
const message = (error: unknown, fallback: string) => (error as { response?: { data?: { message?: string } } })?.response?.data?.message || fallback;

export const RoundsConfigPage = () => {
  const { id: jobId } = useParams<{ id: string }>();
  const [searchParams, setSearchParams] = useSearchParams();
  const navigate = useNavigate();
  const client = useQueryClient();
  const [editing, setEditing] = useState<HiringRound | null>(null);
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState<HiringRoundRequest>(blankRound);
  const [draggedId, setDraggedId] = useState<number | null>(null);
  const { data: job } = useQuery({ queryKey: ['job', jobId], queryFn: () => jobService.getJobById(jobId!), enabled: Boolean(jobId) });
  const { data: rounds = [], isLoading, isError, refetch } = useQuery({ queryKey: ['hiring-rounds', jobId], queryFn: () => hiringRoundService.getRounds(jobId!), enabled: Boolean(jobId) });
  const { data: passPage, isLoading: loadingPass } = useQuery({ queryKey: ['email-templates', 'PASS'], queryFn: () => emailTemplateService.list({ type: 'PASS', activeOnly: true }) });
  const { data: failPage, isLoading: loadingFail } = useQuery({ queryKey: ['email-templates', 'FAIL'], queryFn: () => emailTemplateService.list({ type: 'FAIL', activeOnly: true }) });
  const passTemplates = (passPage?.content ?? []).map(template => ({ id: template.id, name: template.templateName }));
  const failTemplates = (failPage?.content ?? []).map(template => ({ id: template.id, name: template.templateName }));
  const isClosed = job?.status === 'CLOSED';
  const invalidate = () => { void client.invalidateQueries({ queryKey: ['hiring-rounds', jobId] }); void client.invalidateQueries({ queryKey: ['job', jobId] }); };
  const create = useMutation({ mutationFn: (data: HiringRoundRequest) => hiringRoundService.createRound(jobId!, data), onSuccess: () => { toast.success('Đã thêm vòng tuyển dụng'); setCreating(false); invalidate(); }, onError: error => toast.error(message(error, 'Không thể thêm vòng tuyển dụng')) });
  const update = useMutation({ mutationFn: ({ roundId, data }: { roundId: number; data: HiringRoundRequest }) => hiringRoundService.updateRound(jobId!, roundId, data), onSuccess: () => { toast.success('Đã cập nhật vòng tuyển dụng'); setEditing(null); invalidate(); }, onError: error => toast.error(message(error, 'Không thể cập nhật vòng tuyển dụng')) });
  const remove = useMutation({ mutationFn: (roundId: number) => hiringRoundService.deleteRound(jobId!, roundId), onSuccess: invalidate, onError: error => toast.error(message(error, 'Không thể xóa vòng tuyển dụng')) });
  const reorder = useMutation({ mutationFn: (ids: number[]) => hiringRoundService.reorderRounds(jobId!, ids), onSuccess: invalidate, onError: error => toast.error(message(error, 'Không thể đổi thứ tự vòng tuyển dụng')) });
  const openEdit = (round: HiringRound) => { if (isClosed) return; setForm({ name: round.name, description: round.description || '', testLink: round.testLink || '', passEmailTemplateId: round.passEmailTemplateId ?? null, failEmailTemplateId: round.failEmailTemplateId ?? null, isFinalRound: round.isFinalRound }); setEditing(round); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (isClosed || !form.name.trim()) return; const data = { ...form, name: form.name.trim() }; if (creating) create.mutate(data); else if (editing) update.mutate({ roundId: editing.id, data }); };
  const drop = (event: DragEvent<HTMLDivElement>, targetId: number) => { event.preventDefault(); if (isClosed || draggedId === null || draggedId === targetId || reorder.isPending) return; const next = [...rounds]; const from = next.findIndex(round => round.id === draggedId); const to = next.findIndex(round => round.id === targetId); const [moved] = next.splice(from, 1); next.splice(to, 0, moved); reorder.mutate(next.map(round => round.id)); };
  useEffect(() => { const target = rounds.find(round => round.id === Number(searchParams.get('round'))); if (target && !editing && !creating) { openEdit(target); setSearchParams({}); } }, [rounds, searchParams, editing, creating, setSearchParams]);
  const closeModal = () => { setCreating(false); setEditing(null); };
  return <div className="min-h-[calc(100vh-4rem)] bg-[#F8FAFC] p-5 sm:p-8"><div className="mx-auto max-w-4xl space-y-6">
    <header className="flex items-center justify-between"><div className="flex items-center gap-3"><button onClick={() => navigate(`/dashboard/jobs/${jobId}`)}><ArrowLeft /></button><div><h1 className="text-2xl font-extrabold">Cấu hình vòng tuyển dụng</h1><p className="text-sm text-slate-500">{job?.title}</p></div></div><button disabled={isClosed} onClick={() => { setForm(blankRound()); setCreating(true); }} className="inline-flex items-center gap-2 rounded-xl bg-primary-500 px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><Plus className="h-4 w-4" />{isClosed ? 'Job đã đóng' : 'Thêm vòng mới'}</button></header>
    {isClosed && <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800">Job đã ở trạng thái CLOSED. Pipeline đang ở chế độ chỉ đọc.</div>}
    <section className="premium-card bg-white"><div className="border-b px-6 py-4"><h2 className="font-extrabold">Các vòng hiện có</h2><p className="text-xs text-slate-500">{isClosed ? 'Pipeline đang ở chế độ chỉ đọc.' : 'Kéo thả để thay đổi thứ tự.'}</p></div>{isLoading ? <div className="flex justify-center p-12"><Loader2 className="animate-spin" /></div> : isError ? <div className="p-10 text-center text-red-500">Không thể tải danh sách.<button onClick={() => void refetch()} className="ml-2 underline"><RefreshCw className="inline h-4" />Thử lại</button></div> : <div>{rounds.map((round, index) => <div key={round.id} draggable={!isClosed && !reorder.isPending} onDragStart={() => setDraggedId(round.id)} onDragOver={event => event.preventDefault()} onDrop={event => drop(event, round.id)} className="flex items-center gap-3 border-b px-4 py-4"><GripVertical className={isClosed ? 'text-slate-200' : 'cursor-grab text-slate-300'} /><span>{index + 1}</span><div className="flex-1"><b>{round.name}</b>{round.isFinalRound && <span className="ml-2 text-xs text-emerald-600">VÒNG CUỐI</span>}</div><button disabled={isClosed} onClick={() => openEdit(round)}><Pencil className="h-4" /></button><button disabled={isClosed || remove.isPending} onClick={() => window.confirm(`Xóa vòng “${round.name}”?`) && remove.mutate(round.id)}><Trash2 className="h-4" /></button></div>)}</div>}</section>
  </div>{(creating || editing) && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><form onSubmit={submit} className="w-full max-w-xl rounded-2xl bg-white"><div className="flex justify-between border-b p-5"><h2>{creating ? 'Thêm vòng tuyển dụng' : 'Chỉnh sửa vòng tuyển dụng'}</h2><button type="button" onClick={closeModal}><X /></button></div><div className="space-y-4 p-6"><Field label="Tên vòng" value={form.name} onChange={name => setForm({ ...form, name })} required /><label className="block">Mô tả<textarea value={form.description || ''} onChange={event => setForm({ ...form, description: event.target.value })} className="mt-1 min-h-20 w-full rounded border p-2" placeholder="Mục tiêu hoặc nội dung của vòng này" /></label><Field label="Link bài kiểm tra" value={form.testLink || ''} onChange={testLink => setForm({ ...form, testLink })} /><div className="grid gap-4 sm:grid-cols-2"><EmailSelect label="Email Pass" value={form.passEmailTemplateId} templates={passTemplates} loading={loadingPass} emptyLabel="Không gửi email đạt" onChange={passEmailTemplateId => setForm({ ...form, passEmailTemplateId })} /><EmailSelect label="Email False" value={form.failEmailTemplateId} templates={failTemplates} loading={loadingFail} emptyLabel="Không gửi email không đạt" onChange={failEmailTemplateId => setForm({ ...form, failEmailTemplateId })} /></div><p className="text-xs text-slate-500">Danh sách email dùng dữ liệu thật từ US-29.</p><label><input type="checkbox" checked={Boolean(form.isFinalRound)} onChange={event => setForm({ ...form, isFinalRound: event.target.checked })} /> Đánh dấu là vòng cuối</label></div><div className="flex justify-end gap-3 border-t p-5"><button type="button" onClick={closeModal}>Hủy</button><button className="rounded-xl bg-primary-500 px-4 py-2 text-white"><Check className="inline h-4" /> Lưu thay đổi</button></div></form></div>}</div>;
};

const Field = ({ label, value, onChange, required }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) => <label className="block">{label}<input required={required} value={value} onChange={event => onChange(event.target.value)} className="mt-1 w-full rounded border p-2" /></label>;
const EmailSelect = ({ label, value, templates, emptyLabel, onChange, loading }: { label: string; value?: number | null; templates: EmailTemplateOption[]; emptyLabel: string; onChange: (value: number | null) => void; loading: boolean }) => <label>{label}<select disabled={loading} value={value ?? ''} onChange={event => onChange(optionalId(event.target.value))} className="mt-1 w-full rounded border p-2"><option value="">{loading ? 'Đang tải template...' : emptyLabel}</option>{templates.map(template => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label>;
